--11.List Books and Their Authors
-- Write a query to display the title of each book along with the author’s first and last name.
-- VARIANTA MID 

SELECT 
b.TITLE
,a.FIRSTNAME
,a.LASTNAME
FROM BOOKSAUTHORS ba
INNER JOIN BOOKS b
ON b.BOOKID = ba.BOOKID
INNER JOIN AUTHORS a
ON a.AUTHORID = ba.AUTHORID
ORDER BY b.TITLE DESC; 

----- VARIANTA MAI PROFI 
SELECT ba.BOOKID, ba.TITLE, LISTAGG(LASTNAME || ' ' ||  FIRSTNAME, '; ') WITHIN GROUP (ORDER BY FIRSTNAME, LASTNAME) AS AUTHORS
FROM (SELECT 
ba1.BOOKID
,b.TITLE
,a.FIRSTNAME
,a.LASTNAME
FROM BOOKSAUTHORS ba1
INNER JOIN BOOKS b
ON b.BOOKID = ba1.BOOKID
INNER JOIN AUTHORS a
ON a.AUTHORID = ba1.AUTHORID) ba
GROUP BY ba.BOOKID,ba.TITLE
ORDER BY ba.BOOKID  ;